version: "3.9"

services:
  fraud-api:
    image: 861550625988.dkr.ecr.ap-south-1.amazonaws.com/fraud-detection-api:1
    ports:
      - "8000:8000"
    environment:
      MODEL_S3_PATH: ${MODEL_S3_PATH}
      
